//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeServiceWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertCurrency", ReplyAction="http://tempuri.org/IService/ConvertCurrencyResponse")]
        string ConvertCurrency(string toCurrency, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertCurrency", ReplyAction="http://tempuri.org/IService/ConvertCurrencyResponse")]
        System.Threading.Tasks.Task<string> ConvertCurrencyAsync(string toCurrency, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyCodes", ReplyAction="http://tempuri.org/IService/GetCurrencyCodesResponse")]
        string[] GetCurrencyCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyCodes", ReplyAction="http://tempuri.org/IService/GetCurrencyCodesResponse")]
        System.Threading.Tasks.Task<string[]> GetCurrencyCodesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CurrencyExchangeServiceWCF.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CurrencyExchangeServiceWCF.ServiceReference1.IService>, CurrencyExchangeServiceWCF.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertCurrency(string toCurrency, string value) {
            return base.Channel.ConvertCurrency(toCurrency, value);
        }
        
        public System.Threading.Tasks.Task<string> ConvertCurrencyAsync(string toCurrency, string value) {
            return base.Channel.ConvertCurrencyAsync(toCurrency, value);
        }
        
        public string[] GetCurrencyCodes() {
            return base.Channel.GetCurrencyCodes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCurrencyCodesAsync() {
            return base.Channel.GetCurrencyCodesAsync();
        }
    }
}
